"""
On-Policy Distillation Reward Function for LightRFT

This module provides a custom reward function that queries a teacher model
to obtain log probabilities for knowledge distillation during RL training.

The teacher model runs as a separate inference server (vLLM or SGLang),
and this function queries it to get token-level log probabilities for
the sequences generated by the student model.

Key differences from Slime implementation:
- Uses text input (SGLang will tokenize internally)
- Uses async HTTP requests for efficiency
- Includes retry logic for robustness
"""

import asyncio
import aiohttp
import torch
import numpy as np
import logging
from typing import List, Dict, Any, Optional, Union

logger = logging.getLogger(__name__)


async def get_teacher_logprobs_async(
    url: str,
    sequences: List[str],
    session: Optional[aiohttp.ClientSession] = None,
    max_retries: int = 3,
    retry_delay: float = 1.0,
) -> List[Dict[str, Any]]:
    """
    Asynchronously query teacher model for log probabilities.

    :param url: URL of the teacher model inference server
    :type url: str
    :param sequences: List of full sequences (prompt + response)
    :type sequences: List[str]
    :param session: Optional aiohttp session for connection reuse
    :type session: Optional[aiohttp.ClientSession]
    :param max_retries: Maximum number of retry attempts
    :type max_retries: int
    :param retry_delay: Initial delay between retries (exponential backoff)
    :type retry_delay: float
    :return: List of response dictionaries containing log probabilities
    :rtype: List[Dict[str, Any]]
    """
    should_close_session = session is None
    if session is None:
        timeout = aiohttp.ClientTimeout(total=300)  # 5 minute timeout
        session = aiohttp.ClientSession(timeout=timeout)

    async def query_single(sequence: str, attempt: int = 0) -> Dict[str, Any]:
        """Query teacher for a single sequence with retry logic."""
        payload = {
            "text": sequence,
            "sampling_params": {
                "temperature": 0,
                "max_new_tokens": 0,  # Correct SGLang parameter name
                "skip_special_tokens": False,
            },
            "return_logprob": True,
            "logprob_start_len": 0,  # Get logprobs from the beginning
        }

        try:
            async with session.post(url, json=payload) as resp:
                resp.raise_for_status()
                return await resp.json()
        except Exception as e:
            if attempt < max_retries - 1:
                delay = retry_delay * (2 ** attempt)
                logger.warning(
                    f"Teacher query failed (attempt {attempt + 1}/{max_retries}): {e}. "
                    f"Retrying in {delay:.1f}s..."
                )
                await asyncio.sleep(delay)
                return await query_single(sequence, attempt + 1)
            else:
                raise RuntimeError(
                    f"Failed to query teacher model after {max_retries} attempts: {e}"
                ) from e

    try:
        tasks = [query_single(seq) for seq in sequences]
        results = await asyncio.gather(*tasks)
        return results
    finally:
        if should_close_session:
            await session.close()


def extract_teacher_logprobs(
    teacher_responses: List[Dict[str, Any]],
    response_lengths: List[int],
    device: str = "cpu"
) -> List[torch.Tensor]:
    """
    Extract teacher log probabilities for the response tokens only.

    :param teacher_responses: List of teacher model API responses
    :type teacher_responses: List[Dict[str, Any]]
    :param response_lengths: Number of response tokens for each sequence
    :type response_lengths: List[int]
    :param device: Target device for tensors
    :type device: str
    :return: List of tensors containing teacher log probs for response tokens
    :rtype: List[torch.Tensor]
    """
    teacher_log_probs_list = []

    for response, response_length in zip(teacher_responses, response_lengths):
        # Extract log probabilities from teacher response
        # The format depends on the inference server (vLLM/SGLang)
        if "meta_info" in response and "input_token_logprobs" in response["meta_info"]:
            # SGLang format
            logprobs = response["meta_info"]["input_token_logprobs"]
            # logprobs is a list of [logprob, rank, decoded_token] tuples
            # Extract just the logprob values
            logprob_values = [item[0] if isinstance(item, list) else item for item in logprobs]
            # Skip the first token (it doesn't have a logprob from the sequence start)
            # Then take the last response_length tokens
            teacher_log_probs = torch.tensor(logprob_values[1:], dtype=torch.float32)
            teacher_log_probs = teacher_log_probs[-response_length:]
        elif "prompt_logprobs" in response or "token_logprobs" in response:
            # vLLM format
            logprobs = response.get("token_logprobs", response.get("prompt_logprobs", []))
            # Filter out None values and convert to tensor
            logprob_values = [lp for lp in logprobs if lp is not None]
            teacher_log_probs = torch.tensor(logprob_values, dtype=torch.float32)
            teacher_log_probs = teacher_log_probs[-response_length:]
        else:
            raise ValueError(
                f"Unknown response format from teacher model. "
                f"Expected 'meta_info' (SGLang) or 'token_logprobs' (vLLM). "
                f"Got keys: {response.keys()}"
            )

        # Ensure we have the right number of tokens
        if len(teacher_log_probs) < response_length:
            # Pad with zeros if teacher returned fewer logprobs than expected
            padding_length = response_length - len(teacher_log_probs)
            teacher_log_probs = torch.cat([
                torch.zeros(padding_length, dtype=torch.float32),
                teacher_log_probs
            ])

        teacher_log_probs_list.append(teacher_log_probs.to(device))

    return teacher_log_probs_list


def reward_func(queries: List[str], prompts: List[str], **kwargs) -> torch.Tensor:
    """
    Custom reward function for on-policy distillation.

    This function is called by LightRFT's experience maker to compute rewards.
    It returns a placeholder reward tensor. The actual teacher log probs
    are fetched separately by FastExperienceMaker._fetch_teacher_logprobs().

    :param queries: List of full sequences (prompt + response)
    :type queries: List[str]
    :param prompts: List of prompts (unused, for compatibility)
    :type prompts: List[str]
    :return: Placeholder reward tensor (zeros)
    :rtype: torch.Tensor
    """
    # Return placeholder rewards
    # The actual advantage computation happens in OnPolicyDistillationCalculator
    # using teacher log probs stored in experience.info
    return torch.zeros(len(queries), dtype=torch.float32)


async def get_teacher_logprobs_for_experiences(
    teacher_url: str,
    sequences: List[str],
    response_lengths: List[int],
    device: str = "cpu"
) -> torch.Tensor:
    """
    Get teacher log probabilities for a batch of sequences.

    This is the main entry point for obtaining teacher log probs during training.

    :param teacher_url: URL of the teacher model server
    :type teacher_url: str
    :param sequences: List of full sequences (prompt + response)
    :type sequences: List[str]
    :param response_lengths: Number of response tokens for each sequence
    :type response_lengths: List[int]
    :param device: Target device for tensors
    :type device: str
    :return: Tensor of teacher log probs, padded to match max response length
    :rtype: torch.Tensor
    """
    if not sequences:
        return torch.tensor([], device=device)

    # Query teacher model
    responses = await get_teacher_logprobs_async(teacher_url, sequences)

    # Extract log probs
    teacher_log_probs_list = extract_teacher_logprobs(responses, response_lengths, device)

    # Pad to uniform length if needed
    max_length = max(response_lengths)
    padded_log_probs = []
    for log_probs, response_length in zip(teacher_log_probs_list, response_lengths):
        current_len = len(log_probs)
        if current_len < max_length:
            padding = torch.zeros(max_length - current_len, dtype=torch.float32, device=device)
            log_probs = torch.cat([log_probs, padding])
        elif current_len > max_length:
            # Truncate if longer (shouldn't happen, but handle gracefully)
            log_probs = log_probs[:max_length]
        padded_log_probs.append(log_probs)

    return torch.stack(padded_log_probs)


# Synchronous wrapper for compatibility with LightRFT
def get_teacher_logprobs_sync(
    teacher_url: str,
    sequences: List[str],
    response_lengths: List[int],
    device: str = "cpu"
) -> torch.Tensor:
    """
    Synchronous wrapper for getting teacher log probabilities.

    Note: This creates a new event loop, which may conflict with existing loops
    in distributed training environments. Prefer using the async version
    via FastExperienceMaker._fetch_teacher_logprobs() which handles this properly.

    :param teacher_url: URL of the teacher model server
    :type teacher_url: str
    :param sequences: List of full sequences (prompt + response)
    :type sequences: List[str]
    :param response_lengths: Number of response tokens for each sequence
    :type response_lengths: List[int]
    :param device: Target device for tensors
    :type device: str
    :return: Tensor of teacher log probs
    :rtype: torch.Tensor
    """
    try:
        # Try to get existing event loop
        loop = asyncio.get_event_loop()
        if loop.is_running():
            # We're in an async context, need to use different approach
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor() as executor:
                future = executor.submit(
                    asyncio.run,
                    get_teacher_logprobs_for_experiences(
                        teacher_url, sequences, response_lengths, device
                    )
                )
                return future.result()
        else:
            return loop.run_until_complete(
                get_teacher_logprobs_for_experiences(
                    teacher_url, sequences, response_lengths, device
                )
            )
    except RuntimeError:
        # No event loop exists, create one
        return asyncio.run(
            get_teacher_logprobs_for_experiences(
                teacher_url, sequences, response_lengths, device
            )
        )
