"""
On-Policy Distillation Utility Functions for LightRFT

This module provides functions to query a teacher model for log probabilities
used in knowledge distillation during RL training.

The teacher model runs as a separate inference server (SGLang),
and this module queries it to get token-level log probabilities for
the sequences generated by the student model.

Key design decisions (aligned with Slime reference implementation):
- Uses input_ids (not text) to ensure token-level alignment
- Returns per-sample tensors (response tokens only) for dimension alignment
- Includes retry logic for robustness
"""

import asyncio
import aiohttp
import torch
import logging
from typing import List, Dict, Any, Optional

logger = logging.getLogger(__name__)


async def get_teacher_logprobs_by_ids(
    url: str,
    input_ids_list: List[List[int]],
    response_lengths: List[int],
    max_retries: int = 3,
    retry_delay: float = 1.0,
) -> List[torch.Tensor]:
    """
    Query teacher model using input_ids and return per-sample log prob tensors.

    This is the primary function for OPD, using input_ids to ensure exact
    token-level alignment between teacher and student log probabilities.

    :param url: URL of the teacher model inference server (SGLang /generate endpoint)
    :param input_ids_list: List of token id sequences [prompt + response]
    :param response_lengths: Number of response tokens for each sequence
    :param max_retries: Maximum retry attempts per query
    :param retry_delay: Initial delay between retries (exponential backoff)
    :return: List of tensors, each containing teacher log probs for response tokens only
    """
    timeout = aiohttp.ClientTimeout(total=300)
    async with aiohttp.ClientSession(timeout=timeout) as session:

        async def query_single(input_ids: List[int], attempt: int = 0) -> Dict[str, Any]:
            payload = {
                "input_ids": input_ids,
                "sampling_params": {
                    "temperature": 0,
                    "max_new_tokens": 0,
                    "skip_special_tokens": False,
                },
                "return_logprob": True,
                "logprob_start_len": 0,
            }
            try:
                async with session.post(url, json=payload) as resp:
                    resp.raise_for_status()
                    return await resp.json()
            except Exception as e:
                if attempt < max_retries - 1:
                    delay = retry_delay * (2 ** attempt)
                    logger.warning(
                        f"Teacher query failed (attempt {attempt + 1}/{max_retries}): {e}. "
                        f"Retrying in {delay:.1f}s..."
                    )
                    await asyncio.sleep(delay)
                    return await query_single(input_ids, attempt + 1)
                else:
                    raise RuntimeError(
                        f"Failed to query teacher model after {max_retries} attempts: {e}"
                    ) from e

        tasks = [query_single(ids) for ids in input_ids_list]
        results = await asyncio.gather(*tasks)

    # Extract log probs for response tokens only
    teacher_lp_list = []
    for response, resp_len in zip(results, response_lengths):
        logprobs = response["meta_info"]["input_token_logprobs"]
        # Align with Slime: first [1:] to skip BOS/None, then take item[0] for each
        # SGLang returns list of [logprob, token_id] pairs, first element is None (BOS)
        lp_values = [item[0] for item in logprobs[1:]]
        teacher_lp = torch.tensor(lp_values, dtype=torch.float32)
        # Take the last resp_len tokens (response part only)
        teacher_lp = teacher_lp[-resp_len:]
        teacher_lp_list.append(teacher_lp)

    return teacher_lp_list


async def get_teacher_logprobs_async(
    url: str,
    sequences: List[str],
    session: Optional[aiohttp.ClientSession] = None,
    max_retries: int = 3,
    retry_delay: float = 1.0,
) -> List[Dict[str, Any]]:
    """
    [Legacy] Asynchronously query teacher model using text sequences.

    Prefer get_teacher_logprobs_by_ids() for better token-level alignment.
    """
    should_close_session = session is None
    if session is None:
        timeout = aiohttp.ClientTimeout(total=300)
        session = aiohttp.ClientSession(timeout=timeout)

    async def query_single(sequence: str, attempt: int = 0) -> Dict[str, Any]:
        payload = {
            "text": sequence,
            "sampling_params": {
                "temperature": 0,
                "max_new_tokens": 0,
                "skip_special_tokens": False,
            },
            "return_logprob": True,
            "logprob_start_len": 0,
        }
        try:
            async with session.post(url, json=payload) as resp:
                resp.raise_for_status()
                return await resp.json()
        except Exception as e:
            if attempt < max_retries - 1:
                delay = retry_delay * (2 ** attempt)
                logger.warning(
                    f"Teacher query failed (attempt {attempt + 1}/{max_retries}): {e}. "
                    f"Retrying in {delay:.1f}s..."
                )
                await asyncio.sleep(delay)
                return await query_single(sequence, attempt + 1)
            else:
                raise RuntimeError(
                    f"Failed to query teacher model after {max_retries} attempts: {e}"
                ) from e

    try:
        tasks = [query_single(seq) for seq in sequences]
        results = await asyncio.gather(*tasks)
        return results
    finally:
        if should_close_session:
            await session.close()


def extract_teacher_logprobs(
    teacher_responses: List[Dict[str, Any]],
    response_lengths: List[int],
    device: str = "cpu"
) -> List[torch.Tensor]:
    """
    Extract teacher log probabilities for response tokens only.
    """
    teacher_log_probs_list = []

    for response, response_length in zip(teacher_responses, response_lengths):
        if "meta_info" in response and "input_token_logprobs" in response["meta_info"]:
            logprobs = response["meta_info"]["input_token_logprobs"]
            # Align with Slime: first [1:] to skip BOS/None, then take item[0]
            logprob_values = [item[0] for item in logprobs[1:]]
            teacher_log_probs = torch.tensor(logprob_values, dtype=torch.float32)
            teacher_log_probs = teacher_log_probs[-response_length:]
        else:
            raise ValueError(
                f"Unknown response format from teacher model. "
                f"Expected 'meta_info' with 'input_token_logprobs'. "
                f"Got keys: {response.keys()}"
            )

        if len(teacher_log_probs) < response_length:
            padding_length = response_length - len(teacher_log_probs)
            teacher_log_probs = torch.cat([
                torch.zeros(padding_length, dtype=torch.float32),
                teacher_log_probs
            ])

        teacher_log_probs_list.append(teacher_log_probs.to(device))

    return teacher_log_probs_list


def reward_func(queries: List[str], prompts: List[str], **kwargs) -> torch.Tensor:
    """
    Placeholder reward function for on-policy distillation.
    Returns zeros; actual learning signal comes from teacher log probs + task rewards.
    """
    return torch.zeros(len(queries), dtype=torch.float32)


async def get_teacher_logprobs_for_experiences(
    teacher_url: str,
    sequences: List[str],
    response_lengths: List[int],
    device: str = "cpu"
) -> torch.Tensor:
    """
    [Legacy] Get teacher log probabilities using text sequences.

    Prefer get_teacher_logprobs_by_ids() called from _fetch_teacher_logprobs().
    """
    if not sequences:
        return torch.tensor([], device=device)

    responses = await get_teacher_logprobs_async(teacher_url, sequences)
    teacher_log_probs_list = extract_teacher_logprobs(responses, response_lengths, device)

    max_length = max(response_lengths)
    padded_log_probs = []
    for log_probs, response_length in zip(teacher_log_probs_list, response_lengths):
        current_len = len(log_probs)
        if current_len < max_length:
            padding = torch.zeros(max_length - current_len, dtype=torch.float32, device=device)
            log_probs = torch.cat([log_probs, padding])
        elif current_len > max_length:
            log_probs = log_probs[:max_length]
        padded_log_probs.append(log_probs)

    return torch.stack(padded_log_probs)


def get_teacher_logprobs_sync(
    teacher_url: str,
    sequences: List[str],
    response_lengths: List[int],
    device: str = "cpu"
) -> torch.Tensor:
    """
    [Legacy] Synchronous wrapper for text-based teacher log prob queries.
    """
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor() as executor:
                future = executor.submit(
                    asyncio.run,
                    get_teacher_logprobs_for_experiences(
                        teacher_url, sequences, response_lengths, device
                    )
                )
                return future.result()
        else:
            return loop.run_until_complete(
                get_teacher_logprobs_for_experiences(
                    teacher_url, sequences, response_lengths, device
                )
            )
    except RuntimeError:
        return asyncio.run(
            get_teacher_logprobs_for_experiences(
                teacher_url, sequences, response_lengths, device
            )
        )
